//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PileCalc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuLieu
    {
        public int soThuTu { get; set; }
        public int tenLopDat { get; set; }
        public double caoDo { get; set; }
        public double chieuDay { get; set; }
        public double chieuSau { get; set; }
        public int loaiDat { get; set; }
        public int N { get; set; }
        public Nullable<double> ybh1 { get; set; }
        public Nullable<double> li { get; set; }
        public Nullable<double> hi { get; set; }
        public Nullable<double> Su_mui { get; set; }
        public Nullable<double> Db { get; set; }
        public Nullable<double> Sui { get; set; }
        public Nullable<double> ai { get; set; }
        public Nullable<double> ov { get; set; }
        public Nullable<double> Asi { get; set; }
        public Nullable<double> CN { get; set; }
        public Nullable<double> qp { get; set; }
        public Nullable<double> ql { get; set; }
        public Nullable<double> qsi { get; set; }
        public Nullable<double> Ap { get; set; }
        public Nullable<double> N1_60 { get; set; }
        public Nullable<double> N1_60mui { get; set; }
        public Nullable<double> C_Qp { get; set; }
        public Nullable<double> phiqpQp { get; set; }
        public Nullable<double> SumphiqsQsi { get; set; }
        public Nullable<double> C_Qsi { get; set; }
        public Nullable<double> phiqsQsi { get; set; }
        public Nullable<double> QR { get; set; }
        public string tenHoKhoan { get; set; }
        public Nullable<double> temp_Sumov { get; set; }
    
        public virtual SoLieuBanDau SoLieuBanDau { get; set; }
    }
}
