//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PileCalc.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PileCalcPlusEntities : DbContext
    {
        public PileCalcPlusEntities()
            : base("name=PileCalcPlusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SoLieuBanDau> SoLieuBanDaus { get; set; }
        public virtual DbSet<DuLieu> DuLieux { get; set; }
    }
}
