//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PileCalc.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoLieuBanDau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SoLieuBanDau()
        {
            this.DuLieux = new HashSet<DuLieu>();
        }
    
        public string tenHoKhoan { get; set; }
        public string tenHangMuc { get; set; }
        public string tenDuAn { get; set; }
        public string CNDA { get; set; }
        public string nguoiKiemTra { get; set; }
        public string nguoiThucHien { get; set; }
        public int beRongCoc { get; set; }
        public int dienTichMuiCoc { get; set; }
        public int loaiDatNen { get; set; }
        public double khoangCachMatDatTuNhien { get; set; }
        public double chieuSauCocXuyen { get; set; }
        public int Nmui { get; set; }
        public double caoDoMatDat { get; set; }
        public double mucNuocNgam { get; set; }
        public double chieuDaiCoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DuLieu> DuLieux { get; set; }
    }
}
